start:
	docker-compose up -d

stop:
	docker-compose down

build:
	docker-compose up --build

start_2:

	docker-compose -f ./docker-compose-2.yml -p Vier_Lager up -d

build_2:

	docker-compose -f ./docker-compose-2.yml -p Vier_Lager up --build

stop_2:

	docker-compose -f ./docker-compose-2.yml -p Vier_Lager down


start_3:

	docker-compose -f ./docker-compose-3.yml -p Drei_Lager up -d

build_3:

	docker-compose -f ./docker-compose-3.yml -p Drei_Lager up --build

stop_3:

	docker-compose -f ./docker-compose-3.yml -p Drei_Lager down